### ISSUE TITLE
UI doesn't scale to large fonts

### ISSUE THREAD

**Issue by BartMassey** [TeamDelightful/GlassPlateGame#116]
I have poor vision, so I need my big fonts. When the UI is scaled up, the font sizing kind of falls apart.
![gpg-font-scaling-bug](https://user-images.githubusercontent.com/117151/142116146-2f77c1be-a1c4-4ded-b529-2ed7cf12dbe5.png)

There are other UI scaling issues also.

**Comment by kristinbell** [comment]
Hi Bart! I scaled up as much as I could and changed the CSS to accommodate this I hope. Would you mind giving it a spin and let me know if it is better for you or if there are problems?

**Comment by BartMassey** [comment]
Looks like that got that one. Nice!
