### ISSUE TITLE
Install instructions unclear; needs separate config

### ISSUE THREAD

**Issue by BartMassey** [TeamDelightful/GlassPlateGame#117]
The server hostname and port number appear in several places in the code that apparently all have to agree, including at least one place (`app.js`) not listed in the README. I am guessing that those occurrences are all I needed to edit for my installation, but the instructions didn't really say.

The best fix would be to remove all hard-coded hostnames, ip addresses and port numbers from the repository, and instead have a template config file for the user to fill this information in in one place. It would ok if that file was JS and just got imported, as long as it is in one place, small, and reasonably easy to understand and edit.

**Comment by Mcn2** [comment]
Splitting this issue into 2 issues. One for the missing locations, and another for the config file.
