### ISSUE TITLE
Mouseover text for cards is gone

### ISSUE THREAD

**Issue by BartMassey** [TeamDelightful/GlassPlateGame#122]
In an earlier version of the game, mouseover on a card would display the card name. That would be really nice to bring back.

I think we had a meeting where we agreed proper behavior was to show just the card name on mouseover, and its name and full description on click-hold?

**Comment by Mcn2** [comment]
We decided that it was confusing since most cards don't have a description, it felt like a duplicate feature, so we removed it.  Would you like us to add it back in?

**Comment by BartMassey** [comment]
Yes. I feel like it's OK for it to be a duplicate feature. You could put a `*` or something on the end of the mouseover text if there's a definition available…
