### ISSUE TITLE
Leave Game should return to the front page

### ISSUE THREAD

**Issue by BartMassey** [TeamDelightful/GlassPlateGame#123]
Right now pressing the "Leave Game" button returns to a blank page. It should return to the front page in case the user wants to play again.

I don't know what happens when the game is exited by closing the window. If that behaves properly, I think an acceptable fix would be to get rid of the "Leave Game" button altogether.

**Comment by kristinbell** [comment]
Hi! We are working on trying to get everything to exit properly when the user just closes the browser windows, but haven't managed it yet. Right now what "should" happen when the user clicks "Leave Game" is that there should be a sort of logo left at the top of the page and they can click on that to return to the home page. There was is an issue with the fetch/post thing not having enough time to post when we immediately returned to the home page, so the game didn't get deleted, but we might be able to figure out how to work around that...or we hope so.

**Comment by BartMassey** [comment]
What you describe as the current behavior is what happens. Need to make sure that exiting either by this button or by closing the window works properly, though.
