### ISSUE TITLE
Create Game is spammable and confusing

### ISSUE THREAD

**Issue by BartMassey** [TeamDelightful/GlassPlateGame#125]
When "Create Game" is clicked on the front page, a new game is immediately created. This is before the "Join Game" button is pressed in the popup menu, which is in turn before the second "Join Game" button below the username entry on the next screen, which is in turn before the "Start Game" button that appears once cards have been selected.

From the user perspective "game creation" (i.e. the ability for other players to join the game) should only happen once "Start Game" has been pressed: the game ID should not be shown (other than in the URL) before "Start Game". This will prevent accidental creation of a bunch of games by spamming the "Create Game" button, and avoid possible confusion: it looks like right now another player can come along and join the game before the creator finishes and hijack it.

**Comment by kristinbell** [comment]
You are correct. A user who is NOT the original creator of the game can join the game first and select the cards instead. We can eliminate the showing of the gameID on the splash page no problem. We can try to eliminate the option of allowing a different user to create the deck than the original creator. We will have to figure it out though. It might entail having to use cookies. How do you feel about cookies being used?

**Comment by BartMassey** [comment]
I'm fine with cookies if necessary. It would be better without, but sessions may be necessary here.

**Comment by kristinbell** [comment]
What we've figured out so far is to eliminate the drop down box on the create game button and just have that button immediately take the creator to the game page to pick cards. Also, we will not show the game ID on the page until after the cards have been picked. Kind of a withholding information approach to not allowing other users to join until it is time. Does this sound good? Or do. you think we need a more robust way of preventing non-creators from joining too soon?

**Comment by BartMassey** [comment]
Sounds good. I'm not sure I'd even have that card pick page have the game id in the URL; just literally don't create the game until the creator is done picking cards and hits Start Game. Then take them to the game play page with the game id in the URL and show the game ID on that page as you do now.

**Comment by kristinbell** [comment]
Okay, let me see if we can get that to work. I have to do other homework today, so I should be able to tackle it this weekend. I can't make any promises, but we'll see what we can do.
