### ISSUE TITLE
Not all server hostname and port number locations are in the README

### ISSUE THREAD

**Issue by Mcn2** [TeamDelightful/GlassPlateGame#129]
At least present in app.js.
Split from issue #117 

Previous issue text (from Bart):
The server hostname and port number appear in several places in the code that apparently all have to agree, including at least one place (app.js) not listed in the README. I am guessing that those occurrences are all I needed to edit for my installation, but the instructions didn't really say.

**Comment by BartMassey** [comment]
Thank you!
