### ISSUE TITLE
Add Config file for ip addresses and port numbers

### ISSUE THREAD

**Issue by Mcn2** [TeamDelightful/GlassPlateGame#130]
Split from #117 

Previous issue text (From Bart):
The best fix would be to remove all hard-coded hostnames, ip addresses and port numbers from the repository, and instead have a template config file for the user to fill this information in in one place. It would ok if that file was JS and just got imported, as long as it is in one place, small, and reasonably easy to understand and edit.

**Comment by Mcn2** [comment]
We will discuss this change at our next meeting on the 17th

**Comment by BartMassey** [comment]
Thank you!
