### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by BartMassey** [TeamDelightful/GlassPlateGame#131]
Server currently emits a stream of fairly random-looking prints during operation. Logging is a good idea, but should be done in a principled way through a logging crate. Purely debugging log messages should be disabled when running in production.

**Comment by kristinbell** [comment]
Thanks. Yah, we hadn't cleaned up all of the logs yet. Sorry about that. Ooof!

**Comment by kristinbell** [comment]
Hey Bart! If you want to pull a newer version, I've deleted and/or commented out 99% of the annoying log messages. LOL. Sorry we didn't do that earlier.

**Comment by Mcn2** [comment]
Closed with #132

**Comment by BartMassey** [comment]
Yes, those patches cleaned up the noise pretty nicely.

Honestly, having some kind of real logging of connection IPs and the like to a logfile would be a feature. It would help reconstruct the history and usage of the server.
