### ISSUE TITLE
Clicking "Submit" button when choosing deck appends a "Start Game" button and checkboxes

### ISSUE THREAD

**Issue by canthony-pdx** [TeamDelightful/GlassPlateGame#162]
When you choose the "Choose Deck" option, the "Submit" button sticks around and you can keep clicking it to append another "Start Game" button and set of checkboxes

**Comment by kristinbell** [comment]
Oh, I didn't notice this. Thanks. Also, this should get cleared up when Jerry fixes the choose deck radio button option things.
